### PR TITLE
Added creation of test group in database

### PR DESCRIPTION
**Pull request by SergioBertolinSG**
This should fix https://github.com/owncloud/pyocclient/issues/139

### CODE REVIEW

**Comment by SergioBertolinSG** [comment]
@PVince81 stable7 working again. Please review and merge.

**Comment by PVince81** [comment]
Please rebase and squash first. It looks like the commit list contains a few wrong commits ?

**Comment by SergioBertolinSG** [comment]
squashed

**Comment by PVince81** [comment]
:+1:

**Pull request merged**
