### PR TITLE
add depth parameter to enable recursive listing

### PR DESCRIPTION
**Pull request by bobatsar**

### CODE REVIEW

**Comment by PVince81** [comment]
Good idea.

Seems to fail against stable8 for some reason: https://travis-ci.org/owncloud/pyocclient/jobs/142983774
Maybe the infinity mode is broken in stable8. Please note that none of the existing clients are using the infinity mode due to potential performance issues.

**Comment by bobatsar** [comment]
It seems it is not the "infinity" mode which fails, but the test for listing "depth=2".
I tried with the docker image of 8.0 and "infinity" seems to work correctly (lists 6 elements), but depth accepts only 1 as a parameter (returns correctly 5 elements).

depth=2 returns an empty list but should also list 6 elements.

What could be the reason for this?

**Comment by PVince81** [comment]
Not sure, but AFAIK the clients only ever use Depth: 1 or Depth: 0 so it's likely that old versions of OC are buggy with these depths.

Considering that 8.0 only receives security fixes it won't be fixed there.

Can you rebase onto master to get the new travis test env ?

**Comment by PVince81** [comment]
:+1:

**Pull request merged**
