### PR TITLE
Add "get_user" and "edit_user" method

### PR DESCRIPTION
**Pull request by fz6**
get_user implements: https://doc.owncloud.org/server/8.0/admin_manual/configuration_user/user_provisioning_api.html?highlight=provision#users-getuser
edit_user implements: https://doc.owncloud.org/server/8.0/admin_manual/configuration_user/user_provisioning_api.html?highlight=provision#users-edituser

### CODE REVIEW

**Comment by fz6** [comment]
Resolves issue #86

**Comment by PVince81** [comment]
Wow cool. Sorry, I seem to have missed the notification about this PR.

Are you saying that the JSON response is missing the quota elements ?

CC @SergioBertolinSG @jnfrmarks for this nice addition

**Comment by PVince81** [comment]
@fz6 which version did you test against ?

I tested with OC 8.0.3 and the JSON response contains the quota values:
```
  % curl -X GET 'http://root:admin@localhost/owncloud/ocs/v1.php/cloud/users/user1?format=json' | jsonlint -p -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   194  100   194    0     0   1052      0 --:--:-- --:--:-- --:--:--  1054
{
  "ocs": {
    "meta": {
      "status": "ok",
      "statuscode": 100,
      "message": null
    },
    "data": {
      "email": "",
      "enabled": "true",
      "quota": {
        "free": 1071132672,
        "used": 163,
        "total": 1071132835,
        "relative": 0
      },
      "displayname": "user1"
    }
  }
}
```

**Comment by PVince81** [comment]
I'd prefer if we could stick to JSON for parsing the response.
I suspect the reason why JSON didn't contain the quota for you might be a bug in the server that needs to be fixed there.

Would you mind to also add a test for this ? (if not I can do it later if I find some time).
Thanks a lot.

**Comment by PVince81** [comment]
@fz6 any update ? Can you rebase ?
I'm ok with keeping XML.

**Comment by fz6** [comment]
Hi,

Sorry for slow response!

I am quite happy to use JSON, I didn't realise there was an option to get a JSON response (I blame the OwnCloud docs for that ;-))

I will submit a new pull request using JSON soon.

**Comment by PVince81** [comment]
As you like. Others have now used XML too, which is fine.

**Comment by PVince81** [comment]
@fz6 any update ? can you rebase or resubmit the PR with resolved conflicts ?
Thanks

**Comment by PVince81** [comment]
Follow up PR https://github.com/owncloud/pyocclient/pull/138

**Pull request closed without merging**
