### PR TITLE
Added extended info containing tags and favorites

### PR DESCRIPTION
**Pull request by PVince81**
Added extended_info argument to tell the server to include tags and
favorites in the response, then return an ExtendedFileInfo object.

Added function to set tags and favorites on files.

Fixes https://github.com/PVince81/pyocclient/issues/65
- [ ] fix unit tests
- [ ] add fallback / exception case when extended info is not supported (for OC < 8)

@Gomez @soalhn what do you think ?

### CODE REVIEW

**Comment by PVince81** [comment]
Additional idea I got today: instead of having ExtendedFileInfo extend from FileInfo, just keep FileInfo alone, but provide a method get_extended_info() that returns an additional object. That object would contain only tags and favorites.

So calling `list()` with `extended_info=True` would simply populate that extra object.

- [ ] `set_extended_file_info()` should probably use a dictionary instead of kwargs, for convenience (in the future there might be more extended info)

**Comment by PVince81** [comment]
Hmm I wonder if a generic solution would be better: allow for requesting an arbitrary list of Webdav properties, and then make these accessible under FileInfo.getExtraProperties()

CC @nickvergessen

**Comment by nickvergessen** [comment]
Yeah sounds better, while watching with one eye on the tags and comments for 9.0

**Comment by PVince81** [comment]
needs to be redone anyway, closing

**Pull request closed without merging**
