### PR TITLE
Add dav endpoint version support

### PR DESCRIPTION
**Pull request by PVince81**
If the endpoint version is specified in the constructor, use that.
Else read it from the capabilities call.

### CODE REVIEW

**Comment by PVince81** [comment]
Looks like it's not possible to make it skip the whole class that tests DAV v1.

Skipping in setUp only seems to skip the first test. Then the other tests likely aren't running setUp again like in PHP, so the check is not done.

I could use a skip decorator but it needs to be applied on ALL tests.

Need to think of a better way...

**Comment by PVince81** [comment]
Now added a custom decorator to skip the test class in case DAV v1.0 is detected.
Let's see if that works...

**Comment by PVince81** [comment]
All tests passed now, will cleanup the history

**Comment by PVince81** [comment]
@SergioBertolinSG please review

**Comment by SergioBertolinSG** [comment]
Locally i am seeing a couple of failures:

```
...................F..............................................F...............................................
======================================================================
FAIL: test_get_shares_empty (__main__.TestFileAccess)
Test get shares with empty result
----------------------------------------------------------------------
Traceback (most recent call last):
  File "owncloud/test/test.py", line 821, in test_get_shares_empty
    self.assertEquals(shares, [])
AssertionError: Lists differ: [ShareInfo(share_with_displayn... != []

First list contains 2 additional elements.
First extra element 0:
ShareInfo(share_with_displayname=None,mimetype=application/pdf,displayname_owner=admin,name=mcs.pdf link,share_type=3,file_target=/mcs.pdf,url=http://docker.oc.solidgear.es:62237/index.php/s/N8vdEdBClZhmamD,expiration=None,token=N8vdEdBClZhmamD,uid_file_owner=admin,displayname_file_owner=admin,stime=1490798855,share_with=None,storage_id=home::admin,path=/mcs.pdf,file_parent=2,permissions=1,id=63,uid_owner=admin)

Diff is 849 characters long. Set self.maxDiff to None to see it.

======================================================================
FAIL: test_get_shares_empty (__main__.TestFileAccessDav1)
Test get shares with empty result
----------------------------------------------------------------------
Traceback (most recent call last):
  File "owncloud/test/test.py", line 821, in test_get_shares_empty
    self.assertEquals(shares, [])
AssertionError: Lists differ: [ShareInfo(share_with_displayn... != []

First list contains 2 additional elements.
First extra element 0:
ShareInfo(share_with_displayname=None,mimetype=application/pdf,displayname_owner=admin,name=mcs.pdf link,share_type=3,file_target=/mcs.pdf,url=http://docker.oc.solidgear.es:62237/index.php/s/N8vdEdBClZhmamD,expiration=None,token=N8vdEdBClZhmamD,uid_file_owner=admin,displayname_file_owner=admin,stime=1490798855,share_with=None,storage_id=home::admin,path=/mcs.pdf,file_parent=2,permissions=1,id=63,uid_owner=admin)

Diff is 849 characters long. Set self.maxDiff to None to see it.

----------------------------------------------------------------------
Ran 114 tests in 461.181s

FAILED (failures=2)
```

**Comment by PVince81** [comment]
@SergioBertolinSG is the OC env you're testing against clean ?

**Comment by SergioBertolinSG** [comment]
Maybe not, I can try with a different "clean" one.

**Comment by SergioBertolinSG** [comment]
OK, with a clean server it has worked all fine.

**Pull request merged**
