### PR TITLE
Client subclassing

### PR DESCRIPTION
**Pull request by bobatsar**
Make it easier to subclass owncloud Client class. This was specifically needed to override the `_make_ocs_request` method to pass individual parameters to requests.

This was needed to set the request timeout, as the default timeout on windows machines seems to be 20s.

```python
from owncloud import Client

class CloudClient(Client):
    def _make_ocs_request(self, method, service, action, **kwargs):
        kwargs["timeout"] = 2
        return super(CloudClient, self)._make_ocs_request(method, service,
                                                          action, **kwargs)
```

Additionally the code was reformatted to support PEP 8 a little bit more.
Tests run against oc 8.1 and oc 9.1.2

### CODE REVIEW

**Comment by PVince81** [comment]
Cool, looks good and apparently your cleanup didn't break anything 👍

**Comment by bobatsar** [comment]
Yeah, I tested before the PR with the owncloud docker images. That is really cool and very easy.

Nice, thanks for merging. 

How often do you release on PYPI or when do you plan to do the next release?

**Comment by PVince81** [comment]
@bobatsar I don't have any release plans in particular as I do this on the side.

Releasing 0.3 is still on my long todo list from when I have a free hour

**Comment by PVince81** [comment]
@bobatsar ok, thanks for the nudge, I did a release just now: https://pypi.python.org/pypi/pyocclient/0.3

**Comment by bobatsar** [comment]
@PVince81 thanks for the fast update but it seems pip does not support .egg files but only source archives, so it still installs 0.2. See https://packaging.python.org/pip_easy_install/

Could you please upload the sources as well?

Thanks

**Comment by PVince81** [comment]
ok, did a `sdist` now, can you verify ?

**Comment by bobatsar** [comment]
Perfect, just installed version 0.3 via pip
Thanks

**Pull request merged**
