### PR TITLE
Py3.4 compatibility

### PR DESCRIPTION
**Pull request by ethifus**
This pull request introduces Python 3.4 compatibility. It was tested with Python 3.4.3 and Python 2.7.10. I hope it could serve as a base for better Python 3.x support.

### CODE REVIEW

**Comment by PVince81** [comment]
@cosenal mind helping review this ?

@ethifus looks like this breaks CI: https://travis-ci.org/owncloud/pyocclient/jobs/103321288
Does this require additional python packages to be installed upfront ?
You might want to edit .travis.yml https://github.com/owncloud/pyocclient/blob/master/.travis.yml#L13 to add them, if needed.

**Comment by ethifus** [comment]
@PVince81 you right I forgot to add `six` module  to `.travis.yml`.

**Comment by cosenal** [comment]
sure, I'll review tonight

**Comment by PVince81** [comment]
@ethifus can you rebase ? The travis tests now run on docker.

Then you can enable Python3 tests by editing .travis.yml.

**Pull request merged**
