### PR TITLE
Python 3 target for Travis

### PR DESCRIPTION
**Pull request by PVince81**

### CODE REVIEW

**Comment by PVince81** [comment]
Maybe if we had a docker instance for OC https://github.com/owncloud/pyocclient/issues/112 it would be easier. Then Travis could officially use the "python" env instead of "php" env.

**Comment by PVince81** [comment]
There are already docker instances for ownCloud now.

Question is whether Travis is able to run these. Then we can simply use the Python env instead of the PHP one and point pyocclient at the OC docker.

CC @SergioBertolinSG

**Comment by SergioBertolinSG** [comment]
@PVince81 do you mean this one? https://github.com/docker-library/owncloud
Travis supports docker https://docs.travis-ci.com/user/docker/

**Comment by PVince81** [comment]
Nice!

**Comment by PVince81** [comment]
I'll make a separate PR later with the docker approach.

**Comment by PVince81** [comment]
new PR https://github.com/owncloud/pyocclient/pull/169

**Pull request closed without merging**
