### PR TITLE
fix login bug #118

### PR DESCRIPTION
**Pull request by individual-it**
fix login bug #118

### CODE REVIEW

**Comment by PVince81** [comment]
This won't work due to bugs in core. Core returns multiple session cookies when using OCS and the requests library doesn't use the correct one. :frowning: 

I tried it before, see https://github.com/owncloud/pyocclient/pull/53

**Comment by PVince81** [comment]
Ok I see you commented on https://github.com/owncloud/core/issues/12930.
Problem is that we want pyocclient to also work with older OC versions.

It might be possible to get the OC version first from status.php but then it means multiple requests for login. What do you think ?

**Comment by individual-it** [comment]
I had exactly the same idea and just implemented it.
I cannot see any big disadvantage of sending the login details with every request (except of some bytes of overhead)
An other idea would be to get the status code of the WebDAV requests without session.get()
https://github.com/owncloud/pyocclient/blob/master/owncloud/owncloud.py#L280
I haven't tested it but I guess that's where the cookie gets changed

**Comment by individual-it** [comment]
Oh yes, we have to make 2 calls for every login.
1. get the session from status.php
2. check if the login works. In my pull request I've done it by checking the capabilities URL

**Comment by individual-it** [comment]
@PVince81 what do you think about that fix?

**Comment by PVince81** [comment]
Ah yes, I missed the part where you called status.php.

Travis passed, which means this must work on older OC versions too.

Do you mind adding an additional unit test to test the "wrong login" case ?

**Comment by individual-it** [comment]
created a new test case for the wrong login

**Comment by PVince81** [comment]
Fantastic :+1:

**Pull request merged**
