### PR TITLE
Method to return the actual error message if one was given

### LINKED ISSUE #92: ResponseError must have access to the error message
https://github.com/owncloud/smashbox/pull/83#discussion_r30215985

(I think it's a bug, but maybe an enhancement.)

Will try to have a look later.

### PR DESCRIPTION
**Pull request by nickvergessen**
fix #92 

@PVince81

### CODE REVIEW

**Comment by nickvergessen** [comment]
This makes `bin/smash lib/oc-tests/test_shareFile.py -t=1` pass (so it can be used for testing)

**Comment by PVince81** [comment]
Hmm, are you sure that res.text always contains the status code text ? I thought it would contain the body of the response as text.

**Comment by nickvergessen** [comment]
Well it contains the message from the `OC_OCS_Result` but this is exactly what contains the error message?

**Comment by PVince81** [comment]
What happens with WebDAV calls ? Do they also contain the message in res.text ? (might be XML)

**Comment by nickvergessen** [comment]
@PVince81 updated to add an additional method for the resource body, so the initial return is still the same.

**Comment by PVince81** [comment]
So does the WebDAV call put the response in res.text ?

I guess your last fix means that one would only manually access the response text when expecting an exception ? Maybe we need to add WebDAV-specific handling to also parse WebDAV errors out of the XML. We have such cases for example to differentiate 503 Service not available and 503 Storage not available.

That might be more work though, so if you say that this works I'm ok to have this merged first.

**Comment by nickvergessen** [comment]
> That might be more work though, so if you say that this works I'm ok to have this merged first.

Well for now this is enough and helps to get the failing test pass ;)
So I'd prefer this patch, until I we have more time to work on the feature you describe

**Comment by PVince81** [comment]
:+1:

**Pull request merged**
